#define MAX_NICKNAME_SIZE 512
#define MAX_THEME_NAME_SIZE 1024
#define MAX_REQUEST_SIZE 1024
#define MAX_ANSWER_SIZE 1024
#define NICKNAME_FILE "nicknames.txt"
#define QUIZ_FILE "quiz.txt"
#define SCORE_FILE "score.txt"
#define QUESTION_NUM 5
#define MAX_CLIENTS 20